/**
 * Map Blueprint tools - generate map layout blueprints for AI-designed maps.
 * Creates a 2D representation of map design with bases, resources, lanes, and regions.
 */
import { z } from 'zod';
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join } from 'node:path';

interface MapBlueprint {
  map: {
    name: string;
    size: [number, number];
    theme: string;
    players: number;
    symmetry: string;
  };
  bases: Base[];
  expansions: Expansion[];
  lanes: Lane[];
  regions: Region[];
}

interface Base {
  id: string;
  player: number;
  x: number;
  y: number;
  terrainIntent: string;
  resources: {
    minerals: number;
    vespene: number;
  };
}

interface Expansion {
  id: string;
  x: number;
  y: number;
  risk: 'low' | 'medium' | 'high';
  resources?: {
    minerals: number;
    vespene: number;
  };
}

interface Lane {
  from: string;
  to: string;
  width: number;
  intent: string;
}

interface Region {
  id: string;
  x: number;
  y: number;
  radius: number;
  triggerPurpose: string;
}

function generateBlueprintPreview(blueprint: MapBlueprint): string {
  const [width, height] = blueprint.map.size;
  const scale = 4;
  const canvasW = Math.floor(width / scale);
  const canvasH = Math.floor(height / scale);
  
  const grid: string[][] = [];
  for (let y = 0; y < canvasH; y++) {
    grid.push(new Array(canvasW).fill(' '));
  }
  
  for (const base of blueprint.bases) {
    const gx = Math.floor(base.x / scale);
    const gy = Math.floor(base.y / scale);
    if (gx >= 0 && gx < canvasW && gy >= 0 && gy < canvasH) {
      grid[gy][gx] = base.player === 1 ? 'A' : 'B';
    }
  }
  
  for (const exp of blueprint.expansions) {
    const gx = Math.floor(exp.x / scale);
    const gy = Math.floor(exp.y / scale);
    if (gx >= 0 && gx < canvasW && gy >= 0 && gy < canvasH) {
      grid[gy][gx] = exp.risk === 'high' ? '$' : exp.risk === 'medium' ? '*' : '+';
    }
  }
  
  for (const region of blueprint.regions) {
    const gx = Math.floor(region.x / scale);
    const gy = Math.floor(region.y / scale);
    const r = Math.floor(region.radius / scale);
    for (let dy = -r; dy <= r; dy++) {
      for (let dx = -r; dx <= r; dx++) {
        const nx = gx + dx;
        const ny = gy + dy;
        if (nx >= 0 && nx < canvasW && ny >= 0 && ny < canvasH && dx * dx + dy * dy <= r * r) {
          if (grid[ny][nx] === ' ') grid[ny][nx] = '.';
        }
      }
    }
  }
  
  const lines: string[] = [];
  lines.push('+' + '-'.repeat(canvasW) + '+');
  for (const row of grid) {
    lines.push('|' + row.join('') + '|');
  }
  lines.push('+' + '-'.repeat(canvasW) + '+');
  
  return lines.join('\n');
}

function generateBlueprintJson(blueprint: MapBlueprint): string {
  return JSON.stringify(blueprint, null, 2);
}

function generateTerrainEditingGuide(blueprint: any): string {
  const lines: string[] = [];
  
  lines.push('# Terrain Editing Guide');
  lines.push('');
  lines.push(`Map: ${blueprint.map.name}`);
  lines.push(`Size: ${blueprint.map.size[0]}x${blueprint.map.size[1]}`);
  lines.push(`Theme: ${blueprint.map.theme}`);
  lines.push('');
  lines.push('## Player Bases');
  lines.push('');
  
  for (const base of blueprint.bases) {
    lines.push(`### Player ${base.player} Main Base (${base.id})`);
    lines.push(`- Location: (${base.x}, ${base.y})`);
    lines.push(`- Terrain: ${base.terrainIntent}`);
    lines.push(`- Resources: ${base.resources.minerals} mineral patches, ${base.resources.vespene} vespene geysers`);
    lines.push('');
  }
  
  lines.push('## Expansions');
  lines.push('');
  for (const exp of blueprint.expansions) {
    lines.push(`- ${exp.id}: (${exp.x}, ${exp.y}) - Risk: ${exp.risk}`);
    if (exp.resources) {
      lines.push(`  Resources: ${exp.resources.minerals} minerals, ${exp.resources.vespene} vespene`);
    }
  }
  lines.push('');
  
  lines.push('## Attack Routes');
  lines.push('');
  for (const lane of blueprint.lanes) {
    lines.push(`- ${lane.from} -> ${lane.to}`);
    lines.push(`  Width: ${lane.width} tiles`);
    lines.push(`  Intent: ${lane.intent}`);
  }
  lines.push('');
  
  lines.push('## Trigger Regions');
  lines.push('');
  for (const region of blueprint.regions) {
    lines.push(`- ${region.id}: (${region.x}, ${region.y}) radius ${region.radius}`);
    lines.push(`  Purpose: ${region.triggerPurpose}`);
  }
  
  return lines.join('\n');
}

function generateGalaxyCode(blueprint: any): string {
  const lines: string[] = [];
  
  lines.push(`// Map Blueprint: ${blueprint.map.name}`);
  lines.push(`// Generated by SC2 AI Workbench`);
  lines.push('');
  
  lines.push('// Regions');
  for (const region of blueprint.regions) {
    lines.push(`region r_${region.id} = RegionFromId("${region.id}");`);
  }
  lines.push('');
  
  lines.push('// Starting Locations');
  for (const base of blueprint.bases) {
    lines.push(`point p_${base.id} = Point(${base.x}.0, ${base.y}.0);`);
  }
  lines.push('');
  
  lines.push('// Resource Placement');
  lines.push('void PlaceResources() {');
  for (const base of blueprint.bases) {
    lines.push(`    // ${base.id} resources`);
    lines.push(`    UnitCreate(1, "MineralField", ${base.x + 5}.0, ${base.y}.0, 0.0, 0);`);
    lines.push(`    UnitCreate(1, "VespeneGeyser", ${base.x + 7}.0, ${base.y + 2}.0, 0.0, 0);`);
  }
  lines.push('}');
  lines.push('');
  
  return lines.join('\n');
}

export function registerBlueprintTools(server: McpServer): void {
  server.tool(
    'map.generate_blueprint',
    'Generate a map blueprint with bases, expansions, lanes, and regions.',
    {
      mapName: z.string().optional().default('Untitled Map'),
      theme: z.string().optional().default('standard').describe('Map theme (e.g. jungle, desert, space)'),
      players: z.number().optional().default(2),
      width: z.number().optional().default(160),
      height: z.number().optional().default(160),
      gameMode: z.enum(['melee', 'coop', 'campaign', 'arcade', 'survival', 'rpg']).optional().default('melee'),
      symmetry: z.enum(['none', 'horizontal', 'vertical', 'rotational']).optional().default('vertical'),
    },
    async ({ mapName, theme, players, width, height, gameMode, symmetry }) => {
      const bases: Base[] = [];
      const expansions: Expansion[] = [];
      const lanes: Lane[] = [];
      const regions: Region[] = [];
      
      for (let p = 1; p <= players; p++) {
        const isLeft = p <= players / 2;
        const isTop = p % 2 === 1;
        
        bases.push({
          id: `p${p}_main`,
          player: p,
          x: isLeft ? 30 : width - 30,
          y: isTop ? 30 : height - 30,
          terrainIntent: 'high_ground',
          resources: { minerals: 8, vespene: 2 },
        });
        
        expansions.push({
          id: `p${p}_natural`,
          x: isLeft ? 55 : width - 55,
          y: isTop ? 30 : height - 30,
          risk: 'low',
          resources: { minerals: 8, vespene: 2 },
        });
      }
      
      expansions.push({
        id: 'center_gold',
        x: Math.floor(width / 2),
        y: Math.floor(height / 2),
        risk: 'high',
        resources: { minerals: 12, vespene: 3 },
      });
      
      for (let p = 1; p <= players; p++) {
        lanes.push({
          from: `p${p}_main`,
          to: 'center_gold',
          width: 12,
          intent: 'main_attack_route',
        });
      }
      
      regions.push({
        id: 'center_battlefield',
        x: Math.floor(width / 2),
        y: Math.floor(height / 2),
        radius: 20,
        triggerPurpose: 'major_battle',
      });
      
      const blueprint: MapBlueprint = {
        map: {
          name: mapName,
          size: [width, height],
          theme,
          players,
          symmetry,
        },
        bases,
        expansions,
        lanes,
        regions,
      };
      
      const preview = generateBlueprintPreview(blueprint);
      const json = generateBlueprintJson(blueprint);
      const guide = generateTerrainEditingGuide(blueprint);
      const galaxy = generateGalaxyCode(blueprint);
      
      const output: string[] = [
        '=== Map Blueprint Generated ===',
        '',
        `Map: ${mapName}`,
        `Size: ${width}x${height}`,
        `Theme: ${theme}`,
        `Players: ${players}`,
        `Symmetry: ${symmetry}`,
        `Game Mode: ${gameMode}`,
        '',
        '--- Preview ---',
        '',
        preview,
        '',
        'Legend: A/B = Player bases, + = Low risk expansion, * = Medium risk, $ = High risk, . = Region area',
        '',
        '--- Bases ---',
      ];
      
      for (const base of bases) {
        output.push(`  ${base.id}: Player ${base.player} at (${base.x}, ${base.y}) - ${base.terrainIntent}`);
      }
      
      output.push('');
      output.push('--- Expansions ---');
      for (const exp of expansions) {
        output.push(`  ${exp.id}: (${exp.x}, ${exp.y}) - Risk: ${exp.risk}`);
      }
      
      output.push('');
      output.push('--- Attack Routes ---');
      for (const lane of lanes) {
        output.push(`  ${lane.from} -> ${lane.to} (width: ${lane.width})`);
      }
      
      return {
        content: [{
          type: 'text' as const,
          text: output.join('\n')
        }],
        _meta: {
          blueprint: json,
          guide,
          galaxy,
        }
      };
    }
  );

  server.tool(
    'map.save_blueprint',
    'Save a map blueprint to files (JSON, guide, Galaxy code).',
    {
      outputPath: z.string().describe('Output directory'),
      blueprint: z.object({
        map: z.object({
          name: z.string(),
          size: z.tuple([z.number(), z.number()]),
          theme: z.string(),
          players: z.number(),
          symmetry: z.string(),
        }),
        bases: z.array(z.object({
          id: z.string(),
          player: z.number(),
          x: z.number(),
          y: z.number(),
          terrainIntent: z.string(),
          resources: z.object({
            minerals: z.number(),
            vespene: z.number(),
          }),
        })),
        expansions: z.array(z.object({
          id: z.string(),
          x: z.number(),
          y: z.number(),
          risk: z.enum(['low', 'medium', 'high']),
          resources: z.object({
            minerals: z.number(),
            vespene: z.number(),
          }).optional(),
        })),
        lanes: z.array(z.object({
          from: z.string(),
          to: z.string(),
          width: z.number(),
          intent: z.string(),
        })),
        regions: z.array(z.object({
          id: z.string(),
          x: z.number(),
          y: z.number(),
          radius: z.number(),
          triggerPurpose: z.string(),
        })),
      }).describe('Blueprint data'),
    },
    async ({ outputPath, blueprint }) => {
      try {
        if (!existsSync(outputPath)) {
          await mkdir(outputPath, { recursive: true });
        }
        
        const mapName = blueprint.map.name.replace(/\s+/g, '_');
        
        await writeFile(
          join(outputPath, `${mapName}_blueprint.json`),
          JSON.stringify(blueprint, null, 2)
        );
        
        await writeFile(
          join(outputPath, `${mapName}_guide.md`),
          generateTerrainEditingGuide(blueprint)
        );
        
        await writeFile(
          join(outputPath, `${mapName}_blueprint.galaxy`),
          generateGalaxyCode(blueprint)
        );
        
        return {
          content: [{
            type: 'text' as const,
            text: `Blueprint saved!\n\nFiles created:\n- ${mapName}_blueprint.json\n- ${mapName}_guide.md\n- ${mapName}_blueprint.galaxy\n\nLocation: ${outputPath}`
          }]
        };
      } catch (e: any) {
        return { content: [{ type: 'text' as const, text: 'Error saving blueprint: ' + e.message }], isError: true as const };
      }
    }
  );

  server.tool(
    'map.validate_blueprint',
    'Validate a map blueprint for common issues.',
    {
      blueprint: z.object({
        map: z.object({
          name: z.string(),
          size: z.tuple([z.number(), z.number()]),
          theme: z.string(),
          players: z.number(),
          symmetry: z.string(),
        }),
        bases: z.array(z.object({
          id: z.string(),
          player: z.number(),
          x: z.number(),
          y: z.number(),
          terrainIntent: z.string(),
          resources: z.object({
            minerals: z.number(),
            vespene: z.number(),
          }),
        })),
        expansions: z.array(z.object({
          id: z.string(),
          x: z.number(),
          y: z.number(),
          risk: z.enum(['low', 'medium', 'high']),
        })),
        lanes: z.array(z.object({
          from: z.string(),
          to: z.string(),
          width: z.number(),
          intent: z.string(),
        })),
        regions: z.array(z.object({
          id: z.string(),
          x: z.number(),
          y: z.number(),
          radius: z.number(),
          triggerPurpose: z.string(),
        })),
      }),
    },
    async ({ blueprint }) => {
      const issues: string[] = [];
      const warnings: string[] = [];
      
      const [width, height] = blueprint.map.size;
      
      for (const base of blueprint.bases) {
        if (base.x < 0 || base.x >= width || base.y < 0 || base.y >= height) {
          issues.push(`Base ${base.id} is outside map bounds`);
        }
      }
      
      for (const exp of blueprint.expansions) {
        if (exp.x < 0 || exp.x >= width || exp.y < 0 || exp.y >= height) {
          issues.push(`Expansion ${exp.id} is outside map bounds`);
        }
      }
      
      if (blueprint.bases.length < blueprint.map.players) {
        issues.push(`Not enough bases for ${blueprint.map.players} players`);
      }
      
      for (const lane of blueprint.lanes) {
        const fromExists = blueprint.bases.some(b => b.id === lane.from) || blueprint.expansions.some(e => e.id === lane.from);
        const toExists = blueprint.bases.some(b => b.id === lane.to) || blueprint.expansions.some(e => e.id === lane.to);
        if (!fromExists) issues.push(`Lane references unknown location: ${lane.from}`);
        if (!toExists) issues.push(`Lane references unknown location: ${lane.to}`);
      }
      
      if (blueprint.expansions.filter(e => e.risk === 'low').length < blueprint.map.players) {
        warnings.push('Each player should have at least one low-risk expansion');
      }
      
      if (blueprint.lanes.length === 0) {
        warnings.push('No attack routes defined');
      }
      
      const output: string[] = [
        '=== Blueprint Validation ===',
        '',
        `Map: ${blueprint.map.name}`,
        `Players: ${blueprint.map.players}`,
        '',
        `Issues: ${issues.length}`,
        `Warnings: ${warnings.length}`,
      ];
      
      if (issues.length > 0) {
        output.push('', 'Issues:');
        for (const issue of issues) output.push('  - ' + issue);
      }
      
      if (warnings.length > 0) {
        output.push('', 'Warnings:');
        for (const warn of warnings) output.push('  - ' + warn);
      }
      
      if (issues.length === 0 && warnings.length === 0) {
        output.push('', 'Blueprint is valid!');
      }
      
      return { content: [{ type: 'text' as const, text: output.join('\n') }] };
    }
  );
}
