import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import JSZip from "jszip";
import { writeFile } from "node:fs/promises";

function generateDocumentInfo(name, author, description) {
  return `<?xml version="1.0" encoding="utf-8"?>
<DocumentInfo>
  <AuthorName>${author}</AuthorName>
  <DocumentName>${name}</DocumentName>
  <Description>${description}</Description>
  <Expansion>1</Expansion>
  <IsLocked>false</IsLocked>
  <DependentMods/>
  <Dependencies/>
  <RequiredMods/>
</DocumentInfo>`;
}

function generateMapInfo(name, width, height, players) {
  let playerSlots = "";
  for (let i = 0; i < players; i++) {
    playerSlots += `
    <Player id="${i}">
      <Name>Player ${i + 1}</Name>
      <Race>0</Race>
      <Type>1</Type>
      <Team>${i % 2}</Team>
      <StartLocX>${(i % 2 === 0) ? 10 : width - 10}</StartLocX>
      <StartLocY>${(i < 2) ? 10 : height - 10}</StartLocY>
    </Player>`;
  }
  return `<?xml version="1.0" encoding="utf-8"?>
<MapInfo>
  <Name>${name}</Name>
  <Width>${width}</Width>
  <Height>${height}</Height>
  <CameraLeft>0</CameraLeft>
  <CameraRight>${width}</CameraRight>
  <CameraTop>0</CameraTop>
  <CameraBottom>${height}</CameraBottom>
  <Players>${playerSlots}
  </Players>
  <Forces>
    <Force id="0"><Name>Force 1</Name><Team>0</Team></Force>
    <Force id="1"><Name>Force 2</Name><Team>1</Team></Force>
  </Forces>
</MapInfo>`;
}

function generateMapScript(name) {
  return `// MapScript.galaxy - Generated by SC2MCP
// Map: ${name}

void InitLib() {
    // Add initialization code here
}

void main() {
    InitLib();
}
`;
}

export function registerMapCreationTools(server) {
  server.tool(
    "sc2map_create",
    "Create a new SC2Map file from scratch. Generates a valid ZIP that Galaxy Editor can open.",
    {
      outputPath: z.string().describe("Path where to save the .sc2map file"),
      mapName: z.string().describe("Name of the map"),
      author: z.string().optional().default("SC2MCP"),
      description: z.string().optional().default(""),
      width: z.number().optional().default(96),
      height: z.number().optional().default(96),
      players: z.number().optional().default(2),
    },
    async ({ outputPath, mapName, author, description, width, height, players }) => {
      try {
        const zip = new JSZip();
        const headerBuf = Buffer.alloc(64);
        headerBuf.writeUInt32LE(2, 0);
        headerBuf.writeUInt32LE(0, 4);
        headerBuf.writeUInt32LE(players, 8);
        headerBuf.writeUInt32LE(width, 12);
        headerBuf.writeUInt32LE(height, 16);
        zip.file("DocumentHeader", headerBuf);
        zip.file("DocumentInfo", generateDocumentInfo(mapName, author, description));
        zip.file("MapInfo", generateMapInfo(mapName, width, height, players));
        zip.file("MapScript.galaxy", generateMapScript(mapName));
        zip.file("Base.SC2Data", "");
        const output = await zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE", compressionOptions: { level: 9 } });
        await writeFile(outputPath, output);
        return { content: [{ type: "text", text: `SC2Map created: ${outputPath}\nMap: ${mapName}\nSize: ${width}x${height}\nPlayers: ${players}\nFile: ${output.length} bytes\n\nOpen in Galaxy Editor to add terrain and content.` }] };
      } catch (e) {
        return { content: [{ type: "text", text: "Error: " + String(e) }], isError: true };
      }
    }
  );

  server.tool(
    "sc2mod_create",
    "Create a new SC2Mod file from scratch. Mods define reusable game data.",
    {
      outputPath: z.string().describe("Path for the .sc2mod file"),
      modName: z.string().describe("Mod name"),
      author: z.string().optional().default("SC2MCP"),
      description: z.string().optional().default(""),
    },
    async ({ outputPath, modName, author, description }) => {
      try {
        const zip = new JSZip();
        const headerBuf = Buffer.alloc(64);
        headerBuf.writeUInt32LE(2, 0);
        zip.file("DocumentHeader", headerBuf);
        zip.file("DocumentInfo", generateDocumentInfo(modName, author, description));
        zip.file("Base.SC2Data", "<Catalog/>");
        const output = await zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE", compressionOptions: { level: 9 } });
        await writeFile(outputPath, output);
        return { content: [{ type: "text", text: `SC2Mod created: ${outputPath}\nMod: ${modName}` }] };
      } catch (e) {
        return { content: [{ type: "text", text: "Error: " + String(e) }], isError: true };
      }
    }
  );

  server.tool(
    "sc2map_set_dependency",
    "Add a mod dependency to an SC2 map file.",
    {
      archivePath: z.string().describe("Path to the .sc2map file"),
      modPath: z.string().describe("Path or ID of the mod to depend on"),
    },
    async ({ archivePath, modPath }) => {
      try {
        const { readFile } = await import("node:fs/promises");
        const data = await readFile(archivePath);
        const zip = await JSZip.loadAsync(data);
        let docInfo = "";
        const docEntry = zip.file("DocumentInfo");
        if (docEntry) docInfo = await docEntry.async("text");
        docInfo = docInfo.replace("<Dependencies/>", "<Dependencies>\n<Mod>" + modPath + "</Mod>\n</Dependencies>");
        if (!docInfo.includes("<Dependencies>")) {
          docInfo = docInfo.replace("</DocumentInfo>", "<Dependencies><Mod>" + modPath + "</Mod></Dependencies>\n</DocumentInfo>");
        }
        zip.file("DocumentInfo", docInfo);
        const output = await zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE", compressionOptions: { level: 9 } });
        await writeFile(archivePath, output);
        return { content: [{ type: "text", text: "Added dependency: " + modPath }] };
      } catch (e) {
        return { content: [{ type: "text", text: "Error: " + String(e) }], isError: true };
      }
    }
  );
}
